### ISSUE TITLE
multiple sprite images with single vtt file 

### ISSUE THREAD

**Issue by PraveenValaboju** [vlanard/videoscripts#13]
Could you please provide the script file for generating multiple sprite images with single vtt file.

example: if we have the 400 images, we want to create 4 sprite images and 1 vtt file all image description

1 - 100 - sprite_image1.jpg
101 -200 -sprite_image2.jpg
201-300 - sprite_image3.jpg
301-400 - sprite_image4.jpg

and  one vtt file

Thanks,

**Comment by JollyGoal** [comment]
If somebody is still seeking for this feature, you can find it in my [fork](https://github.com/JollyGoal/tooltip_thumb_generator)

**Comment by praveenvalaboju16** [comment]
Thanks @JollyGoal, just tried this one but for the second sprite image the x and y position showing incorrect, actually it should start from 0,0 like first sprite image

00:05:25.000 --> 00:05:35.000
149505_sprite-0.jpg#xywh=640,900,320,180

00:05:35.000 --> 00:05:45.000
149505_sprite-0.jpg#xywh=960,900,320,180

00:05:45.000 --> 00:05:55.000
149505_sprite-0.jpg#xywh=1280,900,320,180

00:05:55.000 --> 00:06:05.000
149505_sprite-1.jpg#xywh=1600,900,320,180

00:06:05.000 --> 00:06:15.000
149505_sprite-1.jpg#xywh=0,1080,320,180

00:06:15.000 --> 00:06:25.000
149505_sprite-1.jpg#xywh=320,1080,320,180

00:06:25.000 --> 00:06:35.000
149505_sprite-1.jpg#xywh=640,1080,320,180

**Comment by PraveenValaboju** [comment]
Thanks @JollyGoal, just tried this one but for the second sprite image the x and y position showing incorrect, actually it should start from 0,0 like first sprite image

First sprite image dimensions in vtt file
WEBVTT

00:00:05.000 --> 00:00:15.000
149505_sprite-0.jpg#xywh=0,0,320,180

00:00:15.000 --> 00:00:25.000
149505_sprite-0.jpg#xywh=320,0,320,180

00:00:25.000 --> 00:00:35.000
149505_sprite-0.jpg#xywh=640,0,320,180

00:00:35.000 --> 00:00:45.000
149505_sprite-0.jpg#xywh=960,0,320,180

00:00:45.000 --> 00:00:55.000
149505_sprite-0.jpg#xywh=1280,0,320,180
--------------------------------------

second sprite image 
---------------------------------
00:05:25.000 --> 00:05:35.000
149505_sprite-0.jpg#xywh=640,900,320,180

00:05:35.000 --> 00:05:45.000
149505_sprite-0.jpg#xywh=960,900,320,180

00:05:45.000 --> 00:05:55.000
149505_sprite-0.jpg#xywh=1280,900,320,180

00:05:55.000 --> 00:06:05.000
149505_sprite-1.jpg#xywh=1600,900,320,180

00:06:05.000 --> 00:06:15.000
149505_sprite-1.jpg#xywh=0,1080,320,180

00:06:15.000 --> 00:06:25.000
149505_sprite-1.jpg#xywh=320,1080,320,180

00:06:25.000 --> 00:06:35.000
149505_sprite-1.jpg#xywh=640,1080,320,180

Thanks in advance

**Comment by PraveenValaboju** [comment]
Thanks @JollyGoal, just tried this one but for the second sprite image the x and y position showing incorrect, actually it should start from 0,0 like first sprite image

First sprite image dimensions in 

---------------------------------
00:05:25.000 --> 00:05:35.000
149505_sprite-0.jpg#xywh=640,900,320,180

00:05:35.000 --> 00:05:45.000
149505_sprite-0.jpg#xywh=960,900,320,180

00:05:45.000 --> 00:05:55.000
149505_sprite-0.jpg#xywh=1280,900,320,180

00:05:55.000 --> 00:06:05.000
149505_sprite-1.jpg#xywh=1600,900,320,180

00:06:05.000 --> 00:06:15.000
149505_sprite-1.jpg#xywh=0,1080,320,180

00:06:15.000 --> 00:06:25.000
149505_sprite-1.jpg#xywh=320,1080,320,180

00:06:25.000 --> 00:06:35.000
149505_sprite-1.jpg#xywh=640,1080,320,180

Thanks in advance

**Comment by PraveenValaboju** [comment]
Thanks @JollyGoal, just tried this one but for the second sprite image the x and y position showing incorrect, actually it should start from 0,0 like first sprite image

First sprite image dimensions in vtt file
WEBVTT

00:00:05.000 --> 00:00:15.000
149505_sprite-0.jpg#xywh=0,0,320,180

00:00:15.000 --> 00:00:25.000
149505_sprite-0.jpg#xywh=320,0,320,180

00:00:25.000 --> 00:00:35.000
149505_sprite-0.jpg#xywh=640,0,320,180

00:00:35.000 --> 00:00:45.000
149505_sprite-0.jpg#xywh=960,0,320,180

00:00:45.000 --> 00:00:55.000
149505_sprite-0.jpg#xywh=1280,0,320,180

second sprite image
00:05:25.000 --> 00:05:35.000
149505_sprite-0.jpg#xywh=640,900,320,180

00:05:35.000 --> 00:05:45.000
149505_sprite-0.jpg#xywh=960,900,320,180

00:05:45.000 --> 00:05:55.000
149505_sprite-0.jpg#xywh=1280,900,320,180

00:05:55.000 --> 00:06:05.000
149505_sprite-1.jpg#xywh=1600,900,320,180

00:06:05.000 --> 00:06:15.000
149505_sprite-1.jpg#xywh=0,1080,320,180

00:06:15.000 --> 00:06:25.000
149505_sprite-1.jpg#xywh=320,1080,320,180

00:06:25.000 --> 00:06:35.000
149505_sprite-1.jpg#xywh=640,1080,320,180

Thanks in advance
