### ISSUE TITLE
Get video from other server

### ISSUE THREAD

**Issue by elalemanyo** [vlanard/videoscripts#6]
Hi,
Will be possible to adapt the code to get  the mp4 from other server?

Thanks!

**Comment by vlanard** [comment]
Via what mechanism? File as http url?

**Comment by elalemanyo** [comment]
yes, http url. The Video is not on my server but I can get it with a request to another server.

**Comment by vlanard** [comment]
Added support in master, via this commit. 
https://github.com/vlanard/videoscripts/commit/a3339719fe94e44a2ffebacb569ceea464786b70
