### ISSUE TITLE
Change output folder

### ISSUE THREAD

**Issue by elalemanyo** [vlanard/videoscripts#7]
Hi,

Will be possible to add a parameter to change where the vtt files are being saved.

Somthing like:

`python makesprites.py [video.mp4] [output_path]`

This will be great.
Thanks!

**Comment by p3rtinax** [comment]
Please this will be great if you add output folder feature,

thanks

**Comment by MahdiZareie** [comment]
I've created a pr for this issue : https://github.com/vlanard/videoscripts/pull/8

**Comment by vlanard** [comment]
Merged PR
